/**
 * ATIVOS_DB — Base de classificação de ativos da B3
 * Fonte: Investidor10 (investidor10.com.br), consultado em 08/07/2026
 *
 * Estrutura:
 * - FIIs: { tipo: "Tijolo" | "Papel" | "Híbrido" | "Fundo de Fundos" | "Fundo Misto" | "Fundo de Desenvolvimento" | "Outro",
 *           segmento: string }
 * - Ações: { setor: string, subsetor: string, segmento: string }
 *
 * Cobertura desta versão:
 * - FIIs: categorias Tijolo, Papel, Híbrido, Fundo de Fundos e Fiagros (~215 tickers)
 * - Ações: Financeiro, Energia Elétrica, Água e Saneamento, Petróleo/Gás, Mineração/Siderurgia,
 *   Saúde, Telecomunicações, Consumo Cíclico/Não Cíclico, Educação, Agronegócio, Tecnologia da
 *   Informação, Bens Industriais e Construção Civil (~223 tickers). Cobre ~161 das 378 ações
 *   mais negociadas da B3 (o restante é cauda longa de baixa liquidez).
 *
 * Isso NÃO é a totalidade da B3 (que tem ~380 ações + ~520 FIIs), mas cobre a grande maioria
 * dos ativos que um investidor pessoa física costuma ter. Ativos não encontrados aqui devem
 * cair no fallback por heurística de sufixo (11 = FII, 3/4/5/6 = Ação) + preenchimento manual.
 */

const ATIVOS_DB = {
  // ==================== FIIs — TIJOLO ====================
  "HGLG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "XPML11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "TRXF11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "BTLG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "XPLG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "KNRI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "VISC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "PVBI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "GARE11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "HGBS11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "GGRC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "BRCR11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "HSML11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "BRCO11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "LVBI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "HGRE11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "ALZR11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "VILG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "RBVA11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "TVRI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Agências Bancárias" },
  "PMLL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "HSLG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "BROF11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "GTWR11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "GSFI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "CPSH11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "KORE11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "RBRP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Outros" },
  "BBIG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "BPML11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "VINO11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "PQAG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "RCRB11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "BTAL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Outros" },
  "RBRL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "HPDP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "XPIN11": { tipo: "FII", subtipo: "Tijolo", segmento: "Outros" },
  "PQDP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "TRBL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "FATN11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "FPAB11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "INLG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "TOPP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "TEPP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "PATL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "RZAT11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "FCFL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Educacional" },
  "HTMX11": { tipo: "FII", subtipo: "Tijolo", segmento: "Hotéis" },
  "FIIB11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "LASC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "CXCO11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "AJFI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "AIEC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "NEWL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "VGRI11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "HGPO11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "VSHO11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "GRUL11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "RBED11": { tipo: "FII", subtipo: "Tijolo", segmento: "Educacional" },
  "CXAG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Agências Bancárias" },
  "NSLU11": { tipo: "FII", subtipo: "Tijolo", segmento: "Hospitalar" },
  "BLMG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Outros" },
  "VCRR11": { tipo: "FII", subtipo: "Tijolo", segmento: "Outros" },
  "RBRK11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "FIGS11": { tipo: "FII", subtipo: "Tijolo", segmento: "Shoppings / Varejo" },
  "CYLD11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "FIIP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "FIIP11B": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "BBRC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Agências Bancárias" },
  "BSLT11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "BTML11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "RBRD11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "PATC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "BMLC11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "DVLP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "ERPA11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "GLOG11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "SPGM11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "RBRS11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "AERO11": { tipo: "FII", subtipo: "Tijolo", segmento: "Logístico / Indústria / Galpões" },
  "BMLT11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },
  "ERCR11": { tipo: "FII", subtipo: "Tijolo", segmento: "Híbrido" },

  // ==================== FIIs — PAPEL ====================
  "KNCR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "KNIP11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "BISE11": { tipo: "FII", subtipo: "Papel", segmento: "Fundo de Infraestrutura (FI-Infra)" },
  "MXRF11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "CPTS11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "KNHY11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "IRIM11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "RECR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "HCTR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "KNUQ11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "BTHF11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "KNSC11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "MCCI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "PCIP11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "RBRR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "HGCR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "VGIR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "VGHF11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "VCJR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "DEVA11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "VRTA11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RBRY11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "URPR11": { tipo: "FII", subtipo: "Papel", segmento: "Outros" },
  "MCRE11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "VGIP11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "BTCI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RZAK11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "HABT11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "XPCI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "JSAF11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "BCRI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "CACR11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "HREC11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "AFHI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "CLIN11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "ICRI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "BARI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "PORD11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RPRI11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "CYCR11": { tipo: "FII", subtipo: "Papel", segmento: "Outros" },
  "KCRE11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "OUJP11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "VSLH11": { tipo: "FII", subtipo: "Papel", segmento: "Outros" },
  "NMKS11": { tipo: "FII", subtipo: "Papel", segmento: "Logístico / Indústria / Galpões" },
  "SAPI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "GAME11": { tipo: "FII", subtipo: "Papel", segmento: "Outros" },
  "HSAF11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RDIV11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "JSCR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "VCRI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "KIVO11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RBHG11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "ALZC11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "PLCR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RBHY11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "ARRI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "RZLC11": { tipo: "FII", subtipo: "Papel", segmento: "Outros" },
  "FYTO11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "NCHB11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "EXES11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "EQIN11": { tipo: "FII", subtipo: "Papel", segmento: "Outros" },
  "GCRI11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "NEXG11": { tipo: "FII", subtipo: "Papel", segmento: "Fiagros" },
  "LKDV11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "OGIN11": { tipo: "FII", subtipo: "Papel", segmento: "Fundo de Infraestrutura (FI-Infra)" },
  "EIRA11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "EDGE11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "IRDM11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },

  // ==================== FIIs — FIAGROS (agronegócio) ====================
  "AGRX11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "RZAG11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "VGIA11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "KNCA11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "GCRA11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "BTAG11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "FGAA11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "RURA11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "VCRA11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "CPTR11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "IAAG11": { tipo: "FII", subtipo: "Fiagro", segmento: "Fiagros" },
  "TGAR11": { tipo: "FII", subtipo: "Papel", segmento: "Títulos e Valores Mobiliários" },
  "CBOP11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },
  "CNES11": { tipo: "FII", subtipo: "Tijolo", segmento: "Lajes Corporativas" },

  // ==================== FIIs — HÍBRIDO (tipo "Outro"/Misto/Desenvolvimento com segmento Híbrido) ====================
  "FTCE11B": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "HGRU11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "GZIT11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "KNHF11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "JSRE11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "RZTR11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "HSRE11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "RECT11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "MFII11": { tipo: "FII", subtipo: "Fundo de Desenvolvimento", segmento: "Híbrido" },
  "CPUR11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "CPOF11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "SARE11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "TRXB11": { tipo: "FII", subtipo: "Fundo de Desenvolvimento", segmento: "Híbrido" },
  "TRXY11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "WHGR11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "RBFM11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "SPXS11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "VVRI11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "PMIS11": { tipo: "FII", subtipo: "Outro", segmento: "Híbrido" },
  "BIPD11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "JPPA11": { tipo: "FII", subtipo: "Papel", segmento: "Híbrido" },
  "SNME11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "HRES11": { tipo: "FII", subtipo: "Fundo de Desenvolvimento", segmento: "Híbrido" },
  "AFHF11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "EMET11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Híbrido" },
  "ASRF11": { tipo: "FII", subtipo: "Fundo de Desenvolvimento", segmento: "Híbrido" },
  "PNPR11": { tipo: "FII", subtipo: "Fundo de Desenvolvimento", segmento: "Híbrido" },

  // ==================== FIIs — FUNDO DE FUNDOS ====================
  "HFOF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "RBRX11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "PSEC11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "JCCJ11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Fundo de Fundos" },
  "RVBI11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "KFOF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "BCIA11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "KISU11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "SNFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "XPSF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "BBFO11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "BPFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "HGFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "BICE11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "OUFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "CXRI11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Híbrido" },
  "ALZM11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "ITIT11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "CPFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Híbrido" },
  "CRFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "BCFF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "RBRF11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "RBRX11": { tipo: "FII", subtipo: "Fundo de Fundos", segmento: "Títulos e Valores Mobiliários" },
  "XPPR11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Outros" },
  "VPPR11": { tipo: "FII", subtipo: "Fundo Misto", segmento: "Outros" },

  // ==================== AÇÕES — FINANCEIRO ====================
  "ITUB4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BPAC11": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BBDC3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BBDC4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "ITSA4": { tipo: "Ação", setor: "Financeiro", subsetor: "Holdings Diversificadas", segmento: "Holdings Diversificadas" },
  "ITSA3": { tipo: "Ação", setor: "Financeiro", subsetor: "Holdings Diversificadas", segmento: "Holdings Diversificadas" },
  "SANB3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "SANB4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BPAN4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BBAS3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "SANB11": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "B3SA3": { tipo: "Ação", setor: "Financeiro", subsetor: "Serviços Financeiros Diversos", segmento: "Serviços Financeiros Diversos" },
  "BBSE3": { tipo: "Ação", setor: "Financeiro", subsetor: "Previdência e Seguros", segmento: "Seguradoras" },
  "CXSE3": { tipo: "Ação", setor: "Financeiro", subsetor: "Previdência e Seguros", segmento: "Seguradoras" },
  "PSSA3": { tipo: "Ação", setor: "Financeiro", subsetor: "Previdência e Seguros", segmento: "Seguradoras" },
  "MULT3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "ALOS3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "BNBR3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BRAP4": { tipo: "Ação", setor: "Financeiro", subsetor: "Holdings Diversificadas", segmento: "Holdings Diversificadas" },
  "BMEB4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "IGTI3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "BRSR6": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "ABCB4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "SIMH3": { tipo: "Ação", setor: "Financeiro", subsetor: "Holdings Diversificadas", segmento: "Holdings Diversificadas" },
  "IRBR3": { tipo: "Ação", setor: "Financeiro", subsetor: "Previdência e Seguros", segmento: "Seguradoras" },
  "BAZA3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "PINE4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BMGB4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BEES3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "LOGG3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "PLPL3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Intermediação Imobiliária" },
  "BSLI3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "BRBI11": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "WIZC3": { tipo: "Ação", setor: "Financeiro", subsetor: "Previdência e Seguros", segmento: "Corretoras de Seguros" },
  "BGIP4": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "PEAB3": { tipo: "Ação", setor: "Financeiro", subsetor: "Holdings Diversificadas", segmento: "Holdings Diversificadas" },
  "SCAR3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "RPAD3": { tipo: "Ação", setor: "Financeiro", subsetor: "Serviços Financeiros Diversos", segmento: "Serviços Financeiros Diversos" },
  "SYNE3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },

  // ==================== AÇÕES — ENERGIA ELÉTRICA ====================
  "AXIA3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CPFE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "EQTL3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ENEV3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CPLE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CPLE6": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "EGIE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CMIG4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ENGI11": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ISAE4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "REDE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "TAEE11": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "TAEE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "TAEE4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ALUP3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ALUP4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CMIG3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "LIGT3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "EQPA3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CEEB3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "AURE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ALUP11": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "EKTR3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ENMT4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CBEE3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CLSC4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "EQMA3B": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "GEPA4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "COCE5": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "EMAE4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CEBR3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "GPAR3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CEED3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "AFLT3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "RNEW4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },

  // ==================== AÇÕES — PETRÓLEO, GÁS E BIOCOMBUSTÍVEIS ====================
  "PETR3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "PETR4": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "PRIO3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "RRRP3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "RECV3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "VBBR3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "UGPA3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "RAIZ4": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },
  "CSAN3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },

  // ==================== AÇÕES — MATERIAIS BÁSICOS (Mineração / Siderurgia) ====================
  "VALE3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Mineração", segmento: "Minerais Metálicos" },
  "BRAP3": { tipo: "Ação", setor: "Financeiro", subsetor: "Holdings Diversificadas", segmento: "Holdings Diversificadas" },
  "GGBR3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Siderurgia" },
  "USIM3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Siderurgia" },
  "CMIN3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Mineração", segmento: "Minerais Metálicos" },
  "CSNA3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Siderurgia" },
  "GGBR4": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Siderurgia" },
  "GOAU4": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Siderurgia" },
  "USIM5": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Siderurgia" },
  "SUZB3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Madeira e Papel", segmento: "Papel e Celulose" },
  "KLBN11": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Madeira e Papel", segmento: "Papel e Celulose" },
  "BRAV3": { tipo: "Ação", setor: "Petróleo, Gás e Biocombustíveis", subsetor: "Petróleo, Gás e Biocombustíveis", segmento: "Exploração, Refino e Distribuição" },

  // ==================== AÇÕES — SAÚDE ====================
  "RDOR3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "HAPV3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "FLRY3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "QUAL3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "SAUD3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "ONCO3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "MATD3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "PNVL3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "HYPE3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "BLAU3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "AALR3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },

  // ==================== AÇÕES — TELECOMUNICAÇÕES ====================
  "VIVT3": { tipo: "Ação", setor: "Telecomunicações", subsetor: "Telecomunicações", segmento: "Telecomunicações" },
  "TIMS3": { tipo: "Ação", setor: "Telecomunicações", subsetor: "Telecomunicações", segmento: "Telecomunicações" },
  "FIQE3": { tipo: "Ação", setor: "Telecomunicações", subsetor: "Telecomunicações", segmento: "Telecomunicações" },
  "DESK3": { tipo: "Ação", setor: "Telecomunicações", subsetor: "Telecomunicações", segmento: "Telecomunicações" },
  "BRIT3": { tipo: "Ação", setor: "Telecomunicações", subsetor: "Telecomunicações", segmento: "Telecomunicações" },

  // ==================== AÇÕES — CONSUMO (CÍCLICO E NÃO CÍCLICO) ====================
  "MGLU3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Eletrodomésticos" },
  "LREN3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Tecidos, Vestuário e Calçados" },
  "RENT3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Aluguel de carros" },
  "VAMO3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Aluguel de carros" },
  "AZUL4": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Transporte Aéreo" },
  "GOLL4": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Transporte Aéreo" },
  "CVCB3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Viagens e Lazer", segmento: "Viagens e Turismo" },
  "ABEV3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Bebidas", segmento: "Cervejas e Refrigerantes" },
  "JBSS3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Carnes e Derivados" },
  "MRFG3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Carnes e Derivados" },
  "BRFS3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Carnes e Derivados" },
  "BEEF3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Carnes e Derivados" },
  "ASAI3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Comércio e Distribuição", segmento: "Alimentos" },
  "CRFB3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Comércio e Distribuição", segmento: "Alimentos" },
  "PCAR3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Comércio e Distribuição", segmento: "Alimentos" },
  "NTCO3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Produtos de Uso Pessoal e de Limpeza", segmento: "Produtos de Uso Pessoal" },
  "SMFT3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Agropecuária", segmento: "Açúcar e Álcool" },

  // ==================== AÇÕES — TECNOLOGIA DA INFORMAÇÃO ====================
  "TOTS3": { tipo: "Ação", setor: "Tecnologia da Informação", subsetor: "Programas e Serviços", segmento: "Programas e Serviços" },
  "LWSA3": { tipo: "Ação", setor: "Tecnologia da Informação", subsetor: "Programas e Serviços", segmento: "Programas e Serviços" },
  "POSI3": { tipo: "Ação", setor: "Tecnologia da Informação", subsetor: "Computadores e Equipamentos", segmento: "Computadores e Equipamentos" },
  "CASH3": { tipo: "Ação", setor: "Tecnologia da Informação", subsetor: "Programas e Serviços", segmento: "Programas e Serviços" },

  // ==================== AÇÕES — BENS INDUSTRIAIS ====================
  "WEGE3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Máquinas e Equipamentos", segmento: "Motores, Compressores e Outros" },
  "EMBR3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Aeronáutico e de Defesa" },
  "RAIL3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Transporte Ferroviário" },
  "CCRO3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Exploração de Rodovias" },
  "ECOR3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Exploração de Rodovias" },
  "STBP3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Serviços de Apoio e Armazenagem" },

  // ==================== AÇÕES — CONSTRUÇÃO CIVIL ====================
  "CYRE3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "EZTC3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "MRVE3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "TEND3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "DIRR3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "CURY3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },

  // ==================== AÇÕES — ÁGUA E SANEAMENTO ====================
  "SBSP3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Água e Saneamento", segmento: "Água e Saneamento" },
  "CSMG3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Água e Saneamento", segmento: "Água e Saneamento" },
  "SAPR3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Água e Saneamento", segmento: "Água e Saneamento" },
  "SAPR4": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Água e Saneamento", segmento: "Água e Saneamento" },
  "SAPR11": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Água e Saneamento", segmento: "Água e Saneamento" },

  // ==================== AÇÕES — ENERGIA ELÉTRICA (complemento) ====================
  "ELET3": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "ELET6": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },
  "CPLE6": { tipo: "Ação", setor: "Utilidade Pública", subsetor: "Energia Elétrica", segmento: "Energia Elétrica" },

  // ==================== AÇÕES — MATERIAIS BÁSICOS (complemento) ====================
  "BRKM5": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Químicos", segmento: "Petroquímicos" },
  "KLBN4": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Madeira e Papel", segmento: "Papel e Celulose" },

  // ==================== AÇÕES — CONSUMO (complemento: vestuário, calçados, varejo) ====================
  "GRND3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Calçados" },
  "ARZZ3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Vestuário" },
  "ALPA4": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Calçados" },
  "SBFG3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Artigos Esportivos" },
  "PETZ3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Produtos Diversos" },
  "AMER3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Eletrodomésticos" },

  // ==================== AÇÕES — EDUCAÇÃO ====================
  "COGN3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Serviços Educacionais" },
  "YDUQ3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Serviços Educacionais" },
  "ANIM3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Serviços Educacionais" },
  "SEER3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Serviços Educacionais" },

  // ==================== AÇÕES — AGRONEGÓCIO ====================
  "AGRO3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Agropecuária", segmento: "Agricultura" },
  "SLCE3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Agropecuária", segmento: "Agricultura" },
  "TTEN3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Agropecuária", segmento: "Agricultura" },
  "MDIA3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Alimentos Diversos" },
  "CAML3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Alimentos Diversos" },
  "VIVA3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Joalheria e Acessórios" },
  "GUAR3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Vestuário" },
  "CEAB3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Tecidos, Vestuário e Calçados" },
  "POMO4": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "TASA4": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Bélico" },
  "LEVE3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "FRAS3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "KEPL3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Máquinas e Equipamentos", segmento: "Máquinas e Equipamentos Industriais" },
  "SOMA3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Vestuário" },
  "TFCO4": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Produtos Diversos" },
  "MOVI3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Diversos", segmento: "Aluguel de carros" },
  "JHSF3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "HBOR3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "EVEN3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "TRIS3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },

  // ==================== AÇÕES — LOTE ADICIONAL (mais líquidas que ainda faltavam) ====================
  "AMBP3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Serviços Diversos", segmento: "Serviços Diversos" },
  "RADL3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "MOTV3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Exploração de Rodovias" },
  "NATU3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Produtos de Uso Pessoal e de Limpeza", segmento: "Produtos de Uso Pessoal" },
  "MBRF3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Alimentos Processados", segmento: "Carnes e Derivados" },
  "GGPS3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Serviços Diversos", segmento: "Serviços Diversos" },
  "GMAT3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Comércio e Distribuição", segmento: "Alimentos" },
  "GFSA3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "MDNE3": { tipo: "Ação", setor: "Construção Civil", subsetor: "Construção Civil", segmento: "Incorporações" },
  "AZZA3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Calçados" },
  "JALL3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Agropecuária", segmento: "Açúcar e Álcool" },
  "PMAM3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Siderurgia e Metalurgia", segmento: "Artefatos de Cobre" },
  "PGMN3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "RAPT4": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "ITUB3": { tipo: "Ação", setor: "Financeiro", subsetor: "Intermediários Financeiros", segmento: "Bancos" },
  "LJQQ3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Material de Construção" },
  "ENJU3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Comércio Eletrônico" },
  "INTB3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Equipamentos Eletroeletrônicos", segmento: "Equipamentos Eletroeletrônicos" },
  "DXCO3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Madeira e Papel", segmento: "Madeira" },
  "BHIA3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Comércio", segmento: "Eletrodomésticos" },
  "IGTI11": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Exploração de Imóveis" },
  "JSLG3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Transporte Rodoviário" },
  "SMTO3": { tipo: "Ação", setor: "Consumo Não Cíclico", subsetor: "Agropecuária", segmento: "Açúcar e Álcool" },
  "POMO3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "MILS3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Serviços Diversos", segmento: "Aluguel de Equipamentos" },
  "VVEO3": { tipo: "Ação", setor: "Saúde", subsetor: "Comércio e Distribuição", segmento: "Medicamentos e Outros Produtos" },
  "KLBN3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Madeira e Papel", segmento: "Papel e Celulose" },
  "MLAS3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Utilidades Domésticas", segmento: "Eletrodomésticos" },
  "VULC3": { tipo: "Ação", setor: "Consumo Cíclico", subsetor: "Tecidos, Vestuário e Calçados", segmento: "Calçados" },
  "DASA3": { tipo: "Ação", setor: "Saúde", subsetor: "Serviços Médicos Hospitalares, Análises e Diagnósticos", segmento: "Serviços Médicos Hospitalares, Análises e Diagnósticos" },
  "CBAV3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Mineração", segmento: "Minerais Metálicos" },
  "HBSA3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Transporte Hidroviário" },
  "MYPK3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "TUPY3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Material de Transporte", segmento: "Material Rodoviário" },
  "ORVR3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Serviços Diversos", segmento: "Serviços Diversos" },
  "RANI3": { tipo: "Ação", setor: "Materiais Básicos", subsetor: "Madeira e Papel", segmento: "Papel e Celulose" },
  "OIBR3": { tipo: "Ação", setor: "Telecomunicações", subsetor: "Telecomunicações", segmento: "Telecomunicações" },
  "ROMI3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Máquinas e Equipamentos", segmento: "Máquinas e Equipamentos Industriais" },
  "TGMA3": { tipo: "Ação", setor: "Bens Industriais", subsetor: "Transporte", segmento: "Serviços de Apoio e Armazenagem" },
  "LPSB3": { tipo: "Ação", setor: "Financeiro", subsetor: "Exploração de Imóveis", segmento: "Intermediação Imobiliária" },
};

/**
 * Fallback por heurística — usar quando o ticker não está no ATIVOS_DB acima.
 * Retorna o tipo provável; segmento/setor ficam em branco para preenchimento manual.
 */
function classificarPorHeuristica(ticker) {
  const t = ticker.toUpperCase().trim();
  const sufixo = t.replace(/^[A-Z]+/, ""); // pega só os números finais

  if (sufixo === "11" || sufixo === "11B") {
    // A maioria dos "11" é FII, mas alguns são units de ações (ex: SANB11, TAEE11, ENGI11, ALUP11)
    // Esses casos já estão mapeados manualmente acima como "Ação".
    return { tipo: "FII", subtipo: null, segmento: null, confianca: "heuristica" };
  }
  if (["3", "4", "5", "6"].includes(sufixo)) {
    return { tipo: "Ação", setor: null, subsetor: null, segmento: null, confianca: "heuristica" };
  }
  if (["34", "35"].includes(sufixo)) {
    return { tipo: "BDR", setor: null, subsetor: null, segmento: null, confianca: "heuristica" };
  }
  return { tipo: null, confianca: "desconhecido" };
}

/**
 * Função principal de classificação: tenta o banco de dados primeiro, cai no fallback depois.
 */
function classificarAtivo(ticker) {
  const t = ticker.toUpperCase().trim();
  if (ATIVOS_DB[t]) {
    return { ...ATIVOS_DB[t], confianca: "base_de_dados" };
  }
  return classificarPorHeuristica(t);
}

// Exporta pra uso no app (ajuste conforme seu sistema de módulos)
if (typeof module !== "undefined" && module.exports) {
  module.exports = { ATIVOS_DB, classificarAtivo, classificarPorHeuristica };
}
